name: CI - Snapshot
run-name: CI snapshot disparada por ${{ github.actor }}

on:   
  # inicia o workflow manualmente
  workflow_dispatch:
jobs:  
  build_back:
    name: Build Back
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
      - name: Upload Zip Backend
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: build/ci_cd_projeto/backend/dist

  build_front:
    name: Build Front
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
      - name: Upload Zip Frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: build/ci_cd_projeto/frontend/dist

  empacotar:
      name: Empacotar
      needs: [build_back, build_front]
      runs-on: ubuntu-latest
      steps:
        - name: Criar Versão / Release e Tag
          uses: softprops/action-gh-release@v2 #não é recomendado usar a versão mais recente, pois pode quebrar o código
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            body: Release
            tag_name: Release
            fail_on_unmatched_files: false
            files: backend.zip,frontend.zip